version: '2'

services:
  site:
    image: personal-site:latest
    ports:
      - "5000:5000"
    container_name: jonny
    volumes:
      - ~/projects/personal-site:/static
    networks:
      - default
  nginx:
    image: benginx:latest
    ports:
      - "80:80"
      - "443:443"
    container_name: benginx
    networks:
      - default

networks:
  default:
    name: nouveau-net
    driver: bridge
volumes:
  static:
