version: '2'

services:
  site:
    image: personal-site:latest
    ports:
      - "5001:5001"
    container_name: jonny
    volumes:
      - ~/projects/personal-site:/static
    command: gunicorn --bind 0.0.0.0:5001 -w 8 src.main:app
    networks:
      - default
    restart: on-failure

  nottfound:
    image: nottfound:latest
    ports:
      - "5002:5002"
    container_name: nottfound
    volumes:
      - ~/projects/nottfound:/static
    command: gunicorn --bind 0.0.0.0:5002 -w 4 src.main:app
    networks:
      - default
    restart: on-failure

  caddy:
    image: caddy:latest
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ~/.certs/mailserver:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/mail.benchung.dev/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
    depends_on:
      - site

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.benchung.dev
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
      - "995:995"  # POP3 (with TLS)
    volumes:
      - ~/.mailserver/mail-data/:/var/mail/
      - ~/.mailserver/mail-state/:/var/mail-state/
      - ~/.mailserver/mail-logs/:/var/log/mail/
      - ~/.mailserver/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ~/.certs/mailserver:/tmp/dms/custom-certs:ro
    environment:
      - ENABLE_FAIL2BAN=1
      - ENABLE_POP3=1

      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/dms/custom-certs/mail.benchung.dev.crt
      - SSL_KEY_PATH=/tmp/dms/custom-certs/mail.benchung.dev.key

      - PERMIT_DOCKER=container
      - SPOOF_PROTECTION=1
      - POSTMASTER_ADDRESS=ben@benchung.dev
      - MARK_SPAM_AS_READ=0

      - ENABLE_OPENDMARC=0
      - ENABLE_POLICYD_SPF=0
      - ENABLE_AMAVIS=0
      - ENABLE_SPAMASSASSIN=01
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    depends_on:
      - caddy
    restart: always

networks:
  default:
    name: nouveau-net
    driver: bridge
volumes:
  static:
  registry:
  mail_certs:
