version: '2'

services:
  site:
    image: personal-site:latest
    ports:
      - "5001:5001"
    container_name: jonny
    volumes:
      - ~/projects/personal-site:/static
    command: gunicorn --bind 0.0.0.0:5001 -w 8 src.main:app
    networks:
      - default
    restart: on-failure

  nottfound:
    image: nottfound:latest
    ports:
      - "5002:5002"
    container_name: nottfound
    volumes:
      - ~/projects/nottfound:/static
    command: gunicorn --bind 0.0.0.0:5002 -w 4 src.main:app
    networks:
      - default
    restart: on-failure

  caddy:
    image: caddy:latest
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ~/.certs/mailserver:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/mail.benchung.dev/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
    depends_on:
      - site

  db:
    image: postgres
    container_name: postgres
    restart: always
    shm_size: 512mb
    volumes:
      - /run/secrets/postgres:/run/secrets/postgres
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres
    volumes:
      - ~/.data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    secrets:
      - postgres

  feud:
    image: ghcr.io/joshzcold/cold-family-feud:1.5.4
    container_name: feud
    restart: always
    ports:
      - "3000:3000"

networks:
  default:
    name: nouveau-net
    driver: bridge
volumes:
  static:
  registry:

secrets:
   postgres:
     file: ~/.data/secrets/postgres
