version: '2'

services:
  site:
    image: personal-site:latest
    ports:
      - "5001:5001"
    container_name: jonny
    volumes:
      - ~/projects/personal-site:/static
    command: gunicorn --bind 0.0.0.0:5001 -w 8 src.main:app
    networks:
      - default
    restart: on-failure

  nottfound:
    image: nottfound:latest
    ports:
      - "5002:5002"
    container_name: nottfound
    volumes:
      - ~/projects/nottfound:/static
    command: gunicorn --bind 0.0.0.0:5002 -w 4 src.main:app
    networks:
      - default
    restart: on-failure

  caddy:
    image: caddy:latest
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - certs_volume/mailserver:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/mail.benchung.dev/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
    depends_on:
      - site

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.benchung.dev
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - certs_volume/mailserver:/etc/letsencrypt/live/mail.benchung.dev/
    environment:
      - ENABLE_FAIL2BAN=1
      # Using letsencrypt for SSL/TLS certificates:
      - SSL_TYPE=letsencrypt
      # Allow sending emails from other docker containers:
      # Beware creating an Open Relay: https://docker-mailserver.github.io/docker-mailserver/latest/config/environment/#permit_docker
      - PERMIT_DOCKER=network
      # You may want to enable this: https://docker-mailserver.github.io/docker-mailserver/latest/config/environment/#spoof_protection
      # See step 6 below, which demonstrates setup with enabled/disabled SPOOF_PROTECTION:
      - SPOOF_PROTECTION=1
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always

networks:
  default:
    name: nouveau-net
    driver: bridge
volumes:
  static:
  registry:
  certs_volume:
    driver_opts:
      type: none
      device: ~/.certs
