version: '2'

services:
  site:
    image: personal-site:latest
    ports:
      - "5001:5001"
    container_name: jonny
    volumes:
      - ~/projects/personal-site:/static
    command: gunicorn --bind 0.0.0.0:5001 -w 8 src.main:app
    networks:
      - default
    restart: on-failure
  caddy:
    image: caddy:latest
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
    depends_on:
      - site

networks:
  default:
    name: nouveau-net
    driver: bridge
volumes:
  static:
  registry:
